### ISSUE TITLE
crash program in uart output

### ISSUE THREAD

**Issue by mohammada315** [ArduPilot/MAVProxy#1093]
dear ardupilot developers
I need to send a uart stream to some other telemetry
for example

mavproxy.py --master=/dev/serial/by-id/usb-Holybro_Durandal_2C0024001151303138363434-if00,115200 --out=/dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_D30AE0FP-if00-port0,57600         

But after the running mavproxy
`Device /dev/ttyUSB0 is dead
Exception in thread main_loop:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/mohamad/.local/lib/python2.7/site-packages/MAVProxy-1.8.42-py2.7.egg/EGG-INFO/scripts/mavproxy.py", line 1094, in main_loop
  File "/home/mohamad/.local/lib/python2.7/site-packages/MAVProxy-1.8.42-py2.7.egg/EGG-INFO/scripts/mavproxy.py", line 808, in process_mavlink
  File "/home/mohamad/.local/lib/python2.7/site-packages/pymavlink/mavutil.py", line 988, in recv
    ret = self.port.read(n)
  File "/home/mohamad/.local/lib/python2.7/site-packages/serial/serialposix.py", line 596, in read
    'device reports readiness to read but returned no data '
SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)
`

Is there a solution for this problem?

**Comment by peterbarker** [comment]
@mohammada315 you almost certainly have something else reading data from that serial port.  Reopen this if you are sure that's not the case.
