### ISSUE TITLE
Pip install mavproxy fails with missing attrdict

### ISSUE THREAD

**Issue by rotu** [ArduPilot/MAVProxy#1180]
Mac OS 13.4
Python 3.11.3
pip 23.0.1

Apparently we're missing a transitive dependency on `attrdict3` via `wxPython`

```
pip install mavproxy
Collecting mavproxy
  Using cached MAVProxy-1.8.60.tar.gz (9.4 MB)
  Preparing metadata (setup.py) ... done
Collecting pymavlink>=2.4.14
  Using cached pymavlink-2.4.38-py3-none-any.whl (11.3 MB)
Collecting pyserial>=3.0
  Using cached pyserial-3.5-py2.py3-none-any.whl (90 kB)
Collecting numpy
  Using cached numpy-1.24.3-cp311-cp311-macosx_11_0_arm64.whl (13.8 MB)
Collecting billiard>=3.5.0
  Using cached billiard-4.1.0-py3-none-any.whl (86 kB)
Collecting gnureadline
  Using cached gnureadline-8.1.2-cp311-cp311-macosx_11_0_arm64.whl (149 kB)
Collecting matplotlib
  Using cached matplotlib-3.7.1-cp311-cp311-macosx_11_0_arm64.whl (7.3 MB)
Collecting opencv-python
  Using cached opencv_python-4.7.0.72-cp37-abi3-macosx_11_0_arm64.whl (32.6 MB)
Collecting lxml
  Using cached lxml-4.9.2-cp311-cp311-macosx_13_0_arm64.whl
Requirement already satisfied: future in ./venv/lib/python3.11/site-packages (from mavproxy) (0.18.3)
Collecting wxPython
  Using cached wxPython-4.2.0.tar.gz (71.0 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/5z/m09m46753_n3thjhdlhnjrpm0000gp/T/pip-install-t1o5wr8r/wxpython_5aecb8bf042348c5b8223bc915d5c476/setup.py", line 27, in <module>
          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName
        File "/private/var/folders/5z/m09m46753_n3thjhdlhnjrpm0000gp/T/pip-install-t1o5wr8r/wxpython_5aecb8bf042348c5b8223bc915d5c476/buildtools/config.py", line 30, in <module>
          from attrdict import AttrDict
      ModuleNotFoundError: No module named 'attrdict'
      [end of output]
```

**Comment by rotu** [comment]
related issues:
- https://github.com/wxWidgets/Phoenix/issues/2225
- https://github.com/wxWidgets/Phoenix/issues/2235
- https://github.com/wxWidgets/Phoenix/issues/2296
