### ISSUE TITLE
MAV FTP not working on Windows

### ISSUE THREAD

**Issue by rmackay9** [ArduPilot/MAVProxy#1270]
We have a report in Copter-4.4 that uploading a 30MB terrain file using MAVFTP takes >30min ([see report here](https://discuss.ardupilot.org/t/terrain-data-loading-on-sd-card-via-mavftp-is-slow/107750/3))

As part of the investigation I attempted to upload a 30MB terrain file (produced using https://terrain.ardupilot.org/) and confirmed that indeed MP does take at least 30min (it only uploaded 1MB of the file in 5min).

To try and determine if MAVProxy was any faster (in the hopes that it would be thus confirming that the issue was in MP) I found that MAVProxy's "ftp" command simply doesn't work at least on windows.

I was running the latest MAVProxy (1.8.66) and the exact procedure was:

- started MAVProxy and connected to a CubeOrange running Copter-4.4.2 (stable)
- copied the N43E143.DAT file to my Desktop
- attempted to ftp to the APM directory (I had also tried uploading to APM/TERRAIN earlier with no success)
- waiting >7min and checked the since of the file, it was still zero

```
STABILIZE> ftp put C:\Users\rmack\Desktop\N43E143.DAT APM/
Putting C:\Users\rmack\Desktop\N43E143.DAT as APM/N43E143.DAT
STABILIZE> ftp list APM
Listing APM
 D LOGS
 D STRG_BAK
 D TERRAIN
 D scripts
   N43E143.DAT  0
   UNKNOWN.bak  16384
```

**Comment by rmackay9** [comment]
I've changed the title to reflect that this is no longer considered a bug but rather an enhancement request.

On the Nov 14th dev call we discussed with Tridge and discovered that MAVFTP's implementation (both within the GCSs and the flight code) has been optimised for downloading (e.g. from the autopilot->GCS) but not for uploading (e.g. GCS->autopilot).

There were two suggestions for improving peformance:

1. send multiple MAVFTP messages from the GCS to the autopilot without waiting for a response.
2. create a new MAVLink message to send longer messages just like we do for downloading.  Currently it seems the MAVFTP messages are only 80bytes long

I will still try @stephendade's suggestion to confirm that the FTP is working on windows even if it is very slow.

**Comment by TimothyGold** [comment]
I just purchased an Argus FPV ROC Wing VTOL that has their FC that has onboard storage of 8GB but no way to get to the SD card...  I discussed this with them and they just told me to load Terrain data via MavFTP...  Every time I try I get about half way and the a CRC exception is thrown..  I also see the new mount option in the latest beta of Mission planner but when I try to load the 30M DAT file it only copies about 964K...  

This is the exception that continues to get thrown..  
Exception of type 'Ionic.Zip.BadCrcException' was thrown.

   at MissionPlanner.Controls.MavFTPUI.<>c__DisplayClass13_0.<UploadFile>b__2(IProgressReporterDialogue iprd) in D:\a\MissionPlanner\MissionPlanner\Controls\MavFTPUI.cs:line 426
   at MissionPlanner.Controls.ProgressReporterDialogue.RunBackgroundOperation(Object o) in D:\a\MissionPlanner\MissionPlanner\ExtLibs\Controls\ProgressReporterDialogue.cs:line 111

I don't know any other way to preload terrain if I don't continuously have a GS connected which there is now way on this one...
