### ISSUE TITLE
Not compatible with Python 3.12 because of deprecated imp module.

### ISSUE THREAD

**Issue by PeterJBurke** [ArduPilot/MAVProxy#1296]
Python 3.12 deprecated the "imp" module used in

MAVProxy/modules/lib/mp_util.py

Running mavproxy.py on MacOS in Python 3.12 throws the error:
ModuleNotFoundError: No module named 'imp'

Trying to manually install the package with (inside Python 3.12):
 pip install imp  
throws the error:
ERROR: Could not find a version that satisfies the requirement imp (from versions: none)
ERROR: No matching distribution found for imp

For discussion about imp module incompatibility with Python 3.12 see:
https://discuss.python.org/t/how-do-i-migrate-from-imp/27885

**Comment by peterbarker** [comment]
I've created a PR to attempt to fix this.

However, I'm not able to test it will locally as the `serial` module has the same problem in it AFAICS.  How are you getting far enough to find this problem in MAVProxy when `serial` has this problem?

```
Python 3.12.0 (main, Oct  4 2023, 06:27:34) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import serial
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/venv-ardupilot/lib/python3.12/site-packages/serial/__init__.py", line 10, in <module>
    from . import utilities, abc, model, marshal, errors, properties, meta, hooks, test, request
  File "/home/vagrant/venv-ardupilot/lib/python3.12/site-packages/serial/utilities/__init__.py", line 5, in <module>
    compatibility.backport()  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vagrant/venv-ardupilot/lib/python3.12/site-packages/serial/utilities/compatibility.py", line 28, in backport
    exec(BACKWARDS_COMPATIBILITY_IMPORTS, frame.f_globals, frame.f_locals)
  File "<string>", line 4, in <module>
  File "/home/vagrant/venv-ardupilot/lib/python3.12/site-packages/future/standard_library/__init__.py", line 65, in <module>
    import imp
ModuleNotFoundError: No module named 'imp'
>>> 

```

@PeterJBurke are you able to test that this resolves your problem?
