### ISSUE TITLE
MAVExplorer map display issue, MacOS

### ISSUE THREAD

**Issue by autonomical** [ArduPilot/MAVProxy#1322]
Following a homebrew 'brew upgrade' MAVExplorer is no longer running correctly on a MacBook Pro mid-2014 running Big Sur MacOS 11.7.10. First issue reported:

richc@MacBook-Pro-2 lib % MAVExplorer.py 
Traceback (most recent call last):
  File "/usr/local/bin/MAVExplorer.py", line 23, in <module>
    from MAVProxy.modules.lib import rline
  File "/usr/local/lib/python3.11/site-packages/MAVProxy/modules/lib/rline.py", line 13, in <module>
    import gnureadline as readline
ModuleNotFoundError: No module named 'gnureadline'
richc@MacBook-Pro-2 lib %

I then did 'pip3 install gnureadline' and then 'pip3 install matplotlib' and it runs kind-of - I can generate graphs but map display doesn't work. Error reported as associated with a deprecation of pkg_resources API:

richc@MacBook-Pro-2 ~ % MAVExplorer.py
/usr/local/bin/MAVExplorer.py:37: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
MAV> ERROR in command []: No module named 'cv2'
ERROR in command []: No module named 'cv2'
ERROR in command []: No module named 'cv2'

Assistance would be appreciated. Note that I am not a developer/programmer but reasonably OK with UNIX (eg. latex, emacs, regex...)

**Comment by srmainwaring** [comment]
@autonomical - apologies for the long delay in responding. For a period the `gnureadline` package did not support newer versions of Python 3 (3.11 and 3.12) because it relied on features that have been deprecated and finally removed. It has since been updated which should resolve this issue (see: https://github.com/ludwigschwardt/python-gnureadline/pull/71).

I'll close this because I believe the issue has been resolved upstream. If you still experience problems please reopen.
