### ISSUE TITLE
MAVCesium module not working

### ISSUE THREAD

**Issue by magicrub** [ArduPilot/MAVProxy#482]
MAVCesium module not working.

 MAVProxy 1.6.2, 
Windows 7
Python 2.7.9

![image](https://user-images.githubusercontent.com/4782875/34849908-ca194f1e-f6d8-11e7-8896-95fa9f271e8f.png)

**Comment by magicrub** [comment]
@peterbarker confirms he has cesium working on his Ubuntu system (unknown update method)
@kd0aij confirms his pip update to mavproxy on his Ubuntu system DOES NOT include cesium

**Comment by SamuelDudley** [comment]
Hi, is that the traceback with moddebug == 3? If not can you please post the traceback of `module load cesium` after first entering `set moddebug 3`. Thanks!

**Comment by magicrub** [comment]
that's with 3

**Comment by magicrub** [comment]
I just tried again and now it says..
![image](https://user-images.githubusercontent.com/4782875/34850655-a931f2a8-f6db-11e7-941a-e5414303aeb2.png)

**Comment by SamuelDudley** [comment]
Sorry, missed your last comment there... Can you check your MAVProxy pip install path and see if there are any files in the mavproxy_cesium directory (within the module directory).

**Comment by magicrub** [comment]
for windows, I don't have one. For Cygwin pip is c\cygwin\bin\pip

**Comment by magicrub** [comment]
![image](https://user-images.githubusercontent.com/4782875/34851163-aebf6ad2-f6dd-11e7-9bf6-7c1c76276b5f.png)

**Comment by magicrub** [comment]
seems a pip update actually did something.

**Comment by kd0aij** [comment]
```
03:29:07 /usr/local/lib/python2.7/dist-packages/MAVProxy/modules/mavproxy_cesium$ ls
app  __init__.py  __init__.pyc
03:29:08 /usr/local/lib/python2.7/dist-packages/MAVProxy/modules/mavproxy_cesium$ ls app
api_keys.txt   cesium_web_server.py   __init__.py   static
api_keys.txt~  cesium_web_server.pyc  __init__.pyc  templates
```

**Comment by magicrub** [comment]
my \programFiles(x86)\MAVProxy does not have a modules folder

**Comment by SamuelDudley** [comment]
Interesting... I don't currently have access to a windows machine to debug for you but I have a Dell laptop on order. When that arrives I can try to reproduce your issue, however it seems to be related to the pip build and only on windows. How immediate is your fix requirement?

**Comment by kd0aij** [comment]
I am on Ubuntu 16.04 and it looks like I have the same problem:
```
STABILIZE> module load cesium
STABILIZE> Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/MAVProxy-1.6.2-py2.7.egg/EGG-INFO/scripts/mavproxy.py", line 279, in load_module
  File "/usr/local/lib/python2.7/dist-packages/MAVProxy-1.6.2-py2.7.egg/EGG-INFO/scripts/mavproxy.py", line 409, in import_package
ImportError: No module named mavproxy_cesium

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/MAVProxy-1.6.2-py2.7.egg/EGG-INFO/scripts/mavproxy.py", line 279, in load_module
  File "/usr/local/lib/python2.7/dist-packages/MAVProxy-1.6.2-py2.7.egg/EGG-INFO/scripts/mavproxy.py", line 409, in import_package
ImportError: No module named cesium

Failed to load module: No module named cesium. Use 'set moddebug 3' in the MAVProxy console to enable traceback
```

**Comment by kd0aij** [comment]
MAVProxy-1.6.2-py2.7.egg does not contain the cesium module

**Comment by stephendade** [comment]
@SamuelDudley  and @magicrub - I've not included cesium module in the Windows installer.

I've never actually tested the cesium module in Windows ... likely missing some pip libraries.

**Comment by magicrub** [comment]
well, what pip libraries are needed? I'll happily install them manually to test!

**Comment by SamuelDudley** [comment]
Only two additional libraries `tornado` and `configparser`

https://github.com/goodrobots/MAVCesium/blob/master/requirements.txt

Let me know how you go :)

**Comment by SamuelDudley** [comment]
FYI you can also run MAVCesium as a seperate standalone application from MAVProxy if required / desired. Just execute https://github.com/goodrobots/MAVCesium/blob/master/app/cesium_web_server.py and provide a TCP/UDP/Serial MAVLink stream

**Comment by mohammada315** [comment]
sorry
Traceback (most recent call last):
File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/usr/lib/python3.8/threading.py", line 870, in run
self._target(self._args, *self._kwargs)
File "/home/mohammad/.local/lib/python3.8/site-packages/MAVProxy-1.8.39-py3.8.egg/MAVProxy/modules/mavproxy_cesium/app/cesium_web_server.py", line 141, in main
File "/home/mohammad/.local/lib/python3.8/site-packages/MAVProxy-1.8.39-py3.8.egg/MAVProxy/modules/mavproxy_cesium/app/cesium_web_server.py", line 104, in start_app
File "/home/mohammad/.local/lib/python3.8/site-packages/tornado-6.2.dev1-py3.8-linux-x86_64.egg/tornado/tcpserver.py", line 152, in listen
self.add_sockets(sockets)
File "/home/mohammad/.local/lib/python3.8/site-packages/tornado-6.2.dev1-py3.8-linux-x86_64.egg/tornado/tcpserver.py", line 165, in add_sockets
self._handlers[sock.fileno()] = add_accept_handler(
File "/home/mohammad/.local/lib/python3.8/site-packages/tornado-6.2.dev1-py3.8-linux-x86_64.egg/tornado/netutil.py", line 246, in add_accept_handler
io_loop = IOLoop.current()
File "/home/mohammad/.local/lib/python3.8/site-packages/tornado-6.2.dev1-py3.8-linux-x86_64.egg/tornado/ioloop.py", line 264, in current
loop = asyncio.get_event_loop()
File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1'.

**Comment by Ryanf55** [comment]
It's working now. At least 3 devs have ran it successfully. This can be closed.

**Comment by peterbarker** [comment]
Thanks @Ryanf55 !
