### ISSUE TITLE
Consider fixing new dep on wx

### ISSUE THREAD

**Issue by peterbarker** [ArduPilot/MAVProxy#592]
https://github.com/ArduPilot/ardupilot/issues/10360 seems to say that the window layout code requires wx and this kills headless use of various utilities.

**Comment by jaxxzer** [comment]
Seconded, on my recent install:

```
$ .local/bin/MAVExplorer.py 
Traceback (most recent call last):
  File ".local/bin/MAVExplorer.py", line 18, in <module>
    from MAVProxy.modules.lib import wxconsole
  File "/home/jacob/.local/lib/python3.7/site-packages/MAVProxy/modules/lib/wxconsole.py", line 11, in <module>
    from MAVProxy.modules.lib import win_layout
  File "/home/jacob/.local/lib/python3.7/site-packages/MAVProxy/modules/lib/win_layout.py", line 4, in <module>
    import os, wx, pickle
ModuleNotFoundError: No module named 'wx'
```
