### ISSUE TITLE
Unicode error on python3

### ISSUE THREAD

**Issue by Jaaaky** [ArduPilot/MAVProxy#710]
Hi,
Running `signing key mypassX` command on mavproxy with python3 give the following error;

`ERROR in command ['key', 'mypassX']: Unicode-objects must be encoded before hashing`

**Comment by Jaaaky** [comment]
The error didn't go away.

"Unicode-objects must be encoded before hashing" I've made sure I'm running the latest master.

**Comment by Jaaaky** [comment]
Here is the debug output
```
Traceback (most recent call last):
  File "./mavproxy.py", line 657, in process_stdin
    fn(args[1:])
  File "/usr/lib64/python3.6/site-packages/MAVProxy/modules/mavproxy_signing.py", line 31, in cmd_signing
    self.cmd_signing_key(args[1:])
  File "/usr/lib64/python3.6/site-packages/MAVProxy/modules/mavproxy_signing.py", line 91, in cmd_signing_key
    key = self.passphrase_to_key(passphrase)
  File "/usr/lib64/python3.6/site-packages/MAVProxy/modules/mavproxy_signing.py", line 43, in passphrase_to_key
    h.update(passphrase)
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by Jaaaky** [comment]
Ah, sorry, it seems mavproxy itself was master but was using old modules.
It's solved.
