### ISSUE TITLE
Link: UDP out is crashable by GCS

### ISSUE THREAD

**Issue by AndKe** [ArduPilot/MAVProxy#733]
To reproduce: 
sim_vehicle.py -v ArduCopter  --out udp:127.0.0.1:14550
(this will also work with mavproxy that receives actual telemetry from connected AP)

until you connect APMPlanner2 it will crash. 
QGC will work fine.

Yes: This is likely something APMPlanner2 sends, but still, MAVProxy module should not crash.
That said: AP2's development is almost stopped, and MAVProxy did not crash on it before.
 
```
sim_vehicle.py -v ArduCopter --out udp:127.0.0.1:14550
SIM_VEHICLE: Start
SIM_VEHICLE: Killing tasks
SIM_VEHICLE: Starting up at 69.775839,19.548929,87,170 (Snarbyeidet)
SIM_VEHICLE: WAF build
SIM_VEHICLE: Configure waf
SIM_VEHICLE: "/home/andre/prog/ardupilot/modules/waf/waf-light" "configure" "--board" "sitl"
Setting top to                           : /home/andre/prog/ardupilot 
Setting out to                           : /home/andre/prog/ardupilot/build 
Autoconfiguration                        : enabled 
Setting board to                         : sitl 
Using toolchain                          : native 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for c flags '-MMD'              : yes 
Checking for cxx flags '-MMD'            : yes 
Checking for need to link with librt     : not necessary 
Checking for feenableexcept              : yes 
Checking for HAVE_CMATH_ISFINITE         : yes 
Checking for HAVE_CMATH_ISINF            : yes 
Checking for HAVE_CMATH_ISNAN            : yes 
Checking for NEED_CMATH_ISFINITE_STD_NAMESPACE : yes 
Checking for NEED_CMATH_ISINF_STD_NAMESPACE    : yes 
Checking for NEED_CMATH_ISNAN_STD_NAMESPACE    : yes 
Checking for header endian.h                   : yes 
Checking for header byteswap.h                 : yes 
Checking for HAVE_MEMRCHR                      : yes 
Checking for program 'python'                  : /usr/bin/python 
Checking for python version >= 2.7.0           : 3.7.5 
Checking for program 'python'                  : /usr/bin/python 
Checking for python version >= 2.7.0           : 3.7.5 
Source is git repository                       : yes 
Update submodules                              : yes 
Checking for program 'git'                     : /usr/bin/git 
Checking for program 'size'                    : /usr/bin/size 
Benchmarks                                     : disabled 
Unit tests                                     : enabled 
Scripting                                      : enabled 
Scripting runtime checks                       : enabled 
Checking for program 'rsync'                   : /usr/bin/rsync 
'configure' finished successfully (1.422s)
SIM_VEHICLE: Building
SIM_VEHICLE: "/home/andre/prog/ardupilot/modules/waf/waf-light" "build" "--target" "bin/arducopter"
Waf: Entering directory `/home/andre/prog/ardupilot/build/sitl'
Embedding file sandbox.lua:libraries/AP_Scripting/scripts/sandbox.lua
Waf: Leaving directory `/home/andre/prog/ardupilot/build/sitl'

BUILD SUMMARY
Build directory: /home/andre/prog/ardupilot/build/sitl
Target          Text     Data    BSS    Total  
-----------------------------------------------
bin/arducopter  2384585  101400  73512  2559497

Build commands will be stored in build/sitl/compile_commands.json
'build' finished successfully (1.459s)
SIM_VEHICLE: Using defaults from (/home/andre/prog/ardupilot/Tools/autotest/default_params/copter.parm)
SIM_VEHICLE: Run ArduCopter
SIM_VEHICLE: "/home/andre/prog/ardupilot/Tools/autotest/run_in_terminal_window.sh" "ArduCopter" "/home/andre/prog/ardupilot/build/sitl/bin/arducopter" "-S" "-I0" "--home" "69.775839,19.548929,87,170" "--model" "+" "--speedup" "1" "--defaults" "/home/andre/prog/ardupilot/Tools/autotest/default_params/copter.parm"
SIM_VEHICLE: Run MavProxy
SIM_VEHICLE: "mavproxy.py" "--master" "tcp:127.0.0.1:5760" "--sitl" "127.0.0.1:5501" "--out" "127.0.0.1:14550" "--out" "127.0.0.1:14551" "--out" "udp:127.0.0.1:14550"
RiTW: Starting ArduCopter : /home/andre/prog/ardupilot/build/sitl/bin/arducopter -S -I0 --home 69.775839,19.548929,87,170 --model + --speedup 1 --defaults /home/andre/prog/ardupilot/Tools/autotest/default_params/copter.parm
/home/andre/.local/lib/python3.7/site-packages/MAVProxy-1.8.5-py3.7.egg/EGG-INFO/scripts/mavproxy.py:19: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  from imp import reload
Connect tcp:127.0.0.1:5760 source_system=255
Log Directory: 
Telemetry log: mav.tlog
Waiting for heartbeat from tcp:127.0.0.1:5760
MAV> APM: Preparing log system
APM: Prepared log system
APM: ArduCopter V4.0.0-dev (9229efbf)
APM: 7dd12cda5ace4781a7fdea9caefcde80
APM: Frame: QUAD
online system 1
STABILIZE> Mode STABILIZE
Received 1179 parameters
Saved 1179 parameters to mav.parm
APM: Barometer 1 calibration complete
bytearray(b'I')bytearray(b'n')bytearray(b'i')bytearray(b't')bytearray(b' ')bytearray(b'G')bytearray(b'y')bytearray(b'r')bytearray(b'o')bytearray(b'*')bytearray(b'*')bytearray(b'*')bytearray(b'\n')bytearray(b'\n')bytearray(b'R')bytearray(b'e')bytearray(b'a')bytearray(b'd')bytearray(b'y')bytearray(b' ')bytearray(b't')bytearray(b'o')bytearray(b' ')bytearray(b'F')bytearray(b'L')bytearray(b'Y')bytearray(b' ')APM: GPS 1: detected as u-blox at 115200 baud
APM: EKF2 IMU0 initial yaw alignment complete
APM: EKF2 IMU1 initial yaw alignment complete
APM: EKF2 IMU0 tilt alignment complete
APM: EKF2 IMU1 tilt alignment complete
APM: ArduCopter V4.0.0-dev (9229efbf)
APM: 7dd12cda5ace4781a7fdea9caefcde80
APM: Frame: QUAD
Exception in thread main_loop:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/andre/.local/lib/python3.7/site-packages/MAVProxy-1.8.5-py3.7.egg/EGG-INFO/scripts/mavproxy.py", line 883, in main_loop
  File "/home/andre/.local/lib/python3.7/site-packages/MAVProxy-1.8.5-py3.7.egg/EGG-INFO/scripts/mavproxy.py", line 625, in process_mavlink
  File "/home/andre/.local/lib/python3.7/site-packages/pymavlink/dialects/v20/ardupilotmega.py", line 12871, in parse_buffer
    m = self.parse_char(s)
  File "/home/andre/.local/lib/python3.7/site-packages/pymavlink/dialects/v20/ardupilotmega.py", line 12808, in parse_char
    m = self.__parse_char_legacy()
  File "/home/andre/.local/lib/python3.7/site-packages/pymavlink/dialects/v20/ardupilotmega.py", line 12858, in __parse_char_legacy
    m = self.decode(mbuf)
  File "/home/andre/.local/lib/python3.7/site-packages/pymavlink/dialects/v20/ardupilotmega.py", line 13040, in decode
    tlist[i] = tlist[i].decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 4: invalid start byte


```

**Comment by AndKe** [comment]
I've found a solution, ISO-8859-1

**Comment by AndKe** [comment]
this is an pymavlink issue.
