### ISSUE TITLE
cannot load restserver

### ISSUE THREAD

**Issue by wx4cb** [ArduPilot/MAVProxy#748]
silly question, but fresh install on a pi with the latest GH code. I'm trying to load the rest server module but it can't be found. I can see it in the source tree and i can see it being built in the output from "python setup.py build install" but i don't know how to run the module.

````
root@raspberrypi:/usr/local/bin# ./mavproxy.py
Auto-detected serial ports are:
/dev/serial/by-id/usb-FTDI_USB__-__Serial-if00-port0
Connecting to /dev/serial/by-id/usb-FTDI_USB__-__Serial-if00-port0
Connect /dev/serial/by-id/usb-FTDI_USB__-__Serial-if00-port0 source_system=255
Failed to load module: No module named terrain. Use 'set moddebug 3' in the MAVProxy console to enable traceback
Log Directory:
Telemetry log: mav.tlog
Waiting for heartbeat from /dev/serial/by-id/usb-FTDI_USB__-__Serial-if00-port0
 MAV> online system 1
MANUAL> Mode MANUAL
fence breach

MANUAL> module list
MANUAL> adsb: ADS-B data support
arm: arm/disarm handling
auxopt: auxopt command handling
battery: battery commands
calibration: calibration handling
cmdlong: cmdlong handling
fence: geo-fence management
layout: window layout handling
link: link control
log: log transfer
misc: misc commands
mode: mode handling
output: output control
param: parameter handling
rally: rally point control
rc: rc command handling
relay: relay handling
signing: signing control
tuneopt: tuneopt command handling
wp: waypoint handling


MANUAL> module load restserver
MANUAL> Traceback (most recent call last):
  File "/root/.local/lib/python2.7/site-packages/MAVProxy-1.8.18-py2.7.egg/EGG-INFO/scripts/mavproxy.py", line 406, in load_module
  File "/root/.local/lib/python2.7/site-packages/MAVProxy-1.8.18-py2.7.egg/EGG-INFO/scripts/mavproxy.py", line 563, in import_package
  File "build/bdist.linux-armv7l/egg/MAVProxy/modules/mavproxy_restserver.py", line 14, in <module>
ImportError: No module named flask

Traceback (most recent call last):
  File "/root/.local/lib/python2.7/site-packages/MAVProxy-1.8.18-py2.7.egg/EGG-INFO/scripts/mavproxy.py", line 406, in load_module
  File "/root/.local/lib/python2.7/site-packages/MAVProxy-1.8.18-py2.7.egg/EGG-INFO/scripts/mavproxy.py", line 563, in import_package
ImportError: No module named restserver

Failed to load module: No module named restserver.
````

**Comment by stephendade** [comment]
you'll need to do a ``pip install flask --user``, as the flask package is required for the restserver module
