### ISSUE TITLE
MAVExplorer map is not loading on macOS

### ISSUE THREAD

**Issue by srmainwaring** [ArduPilot/MAVProxy#869]
The MAVExplorer map module is not loading correctly on macOS.

Steps to replicate:

1. Run MAVExplorer and load a log:

```bash
$ mavexplorer.py
```

2. Select the map from the menu `Display > Map`:

```console
Warning: reusing colours!
Warning: reusing colours!
Looking for types ['MISSION_ITEM', 'CMD', 'POS', 'GLOBAL_POSITION_INT']
Warning: reusing colours!
Warning: reusing colours!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/usr/local/Cellar/python@3.9/3.9.1_7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/synchronize.py", line 110, in __setstate__
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by srmainwaring** [comment]
Duplicate of #874
