### ISSUE TITLE
Unable to open graphs with MAVProxy due to type errors

### ISSUE THREAD

**Issue by WickedShell** [ArduPilot/MAVProxy#992]
```
FBWA> Adding graph: ['RC_CHANNELS.chan1_raw']
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wickedshell/.local/lib/python3.10/site-packages/MAVProxy/modules/lib/live_graph.py", line 56, in child_task
    app.frame = live_graph_ui.GraphFrame(state=self)
  File "/home/wickedshell/.local/lib/python3.10/site-packages/MAVProxy/modules/lib/live_graph_ui.py", line 28, in __init__
    self.redraw_timer.Start(1000*self.state.tickresolution)
TypeError: Timer.Start(): argument 1 has unexpected type 'float'
```

Information:
```
[wickedshell@lackey ~]$ pip show matplotlib
Name: matplotlib
Version: 3.5.1
Summary: Python plotting package
Home-page: https://matplotlib.org
Author: John D. Hunter, Michael Droettboom
Author-email: matplotlib-users@python.org
License: PSF
Location: /home/wickedshell/.local/lib/python3.10/site-packages
Requires: pillow, numpy, pyparsing, python-dateutil, cycler, kiwisolver, packaging, fonttools
Required-by: 
[wickedshell@lackey ~]$ python --version
Python 3.10.1
```

**Comment by tridge** [comment]
fixed by #993
